### ISSUE TITLE
I just don't know

### ISSUE THREAD

**Issue by acalleia** [danielwbeebe/My-News-Bubble-App#5]
Your code is really clear and concise. Hell each function is documented and explained, I don't know what I could really tell you to change. While working on your css what made you switch in-between  em, vw and px? did you just want some things to stay static?

**Comment by danielwbeebe** [comment]
In general, I prefer defining things with a specific px.  Exceptions include line spacing where defining it by em just feels more intuitive because I think of it like line spacing options in MS Word when you can set spacing to a certain percentage of the font-size - I generally like something somewhere between single space and double space.  As for vh, I only used that for body just to make sure it fills the browser.
